# Generated by Django 3.2.9 on 2021-11-24 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sidgroup',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='رقم المجموعه'),
        ),
        migrations.AddField(
            model_name='student',
            name='Sidnumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='الرقم القومي'),
        ),
        migrations.AddField(
            model_name='student',
            name='Sstatus',
            field=models.BooleanField(blank=True, null=True, verbose_name='حالة الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sinit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
