# Generated by Django 3.2.9 on 2021-11-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_sidnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Sidnumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='الرقم القومي'),
        ),
    ]
