# Generated by Django 3.2.9 on 2021-11-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_sidnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sinit',
        ),
    ]
