# Generated by Django 3.2.9 on 2021-11-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20211127_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sstatus',
            field=models.BooleanField(blank=True, null=True, verbose_name='حالة الطالب'),
        ),
    ]
