# Generated by Django 3.2.9 on 2021-12-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_exams_exam'),
        ('students', '0011_auto_20211210_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='finishExam',
            field=models.ManyToManyField(to='tasks.exam', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='finishedHomework',
            field=models.ManyToManyField(to='tasks.task', verbose_name='الواجبات التي تم ارسالها'),
        ),
    ]
