# Generated by Django 3.2.9 on 2021-12-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_exams_exam'),
        ('home', '0003_auto_20211129_0756'),
        ('students', '0012_auto_20211210_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='finishExam',
            field=models.ManyToManyField(to='tasks.exam', verbose_name='الإمتحانات التي تم ارسالها'),
        ),
        migrations.AlterField(
            model_name='student',
            name='finishedHomework',
            field=models.ManyToManyField(to='home.Lessons', verbose_name='الواجبات التي تم ارسالها'),
        ),
    ]
