# Generated by Django 3.2.9 on 2021-12-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20211210_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Spercent',
            field=models.IntegerField(default=0, verbose_name='نسبة الطالب'),
        ),
    ]
