# Generated by Django 3.2.9 on 2021-12-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_spercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Spercentexams',
            field=models.IntegerField(default=0, verbose_name='نسبة الطالب'),
        ),
        migrations.AddField(
            model_name='student',
            name='Spercenthomeworks',
            field=models.IntegerField(default=0, verbose_name='نسبة حل الواجبات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Spercent',
            field=models.IntegerField(default=0, verbose_name='نسبة حل الامتحانات'),
        ),
    ]
