# Generated by Django 3.2.9 on 2021-12-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20211213_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sexams',
            field=models.IntegerField(default=0, verbose_name='نسبة حل الامتحانات'),
        ),
        migrations.AddField(
            model_name='student',
            name='shomeworks',
            field=models.IntegerField(default=0, verbose_name='نسبة حل الواجبات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Spercent',
            field=models.IntegerField(default=0, verbose_name='نسبة الطالب '),
        ),
        migrations.AlterField(
            model_name='student',
            name='Spercentexams',
            field=models.IntegerField(default=0, verbose_name='نسبة حل الامتحانات'),
        ),
    ]
