# Generated by Django 3.2.9 on 2021-12-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20211213_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sexams',
            field=models.IntegerField(default=0, verbose_name=' حل الامتحانات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='shomeworks',
            field=models.IntegerField(default=0, verbose_name=' حل الواجبات'),
        ),
    ]
