# Generated by Django 3.2.9 on 2021-12-15 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20211213_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'الطالب', 'verbose_name_plural': 'الطلاب'},
        ),
    ]
