# Generated by Django 3.2.9 on 2022-07-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.BigIntegerField(default=10, verbose_name='النقاط'),
        ),
    ]
