# Generated by Django 3.2.9 on 2022-07-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_lessons_isfinished'),
        ('students', '0021_student_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Sstatus',
        ),
        migrations.RemoveField(
            model_name='student',
            name='finishedHomework',
        ),
        migrations.AddField(
            model_name='student',
            name='watchedlecs',
            field=models.ManyToManyField(blank=True, to='home.Lessons', verbose_name='المحاضرات المنتهيه'),
        ),
    ]
