# Generated by Django 3.2.9 on 2022-07-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_lessons_isfinished'),
        ('students', '0022_auto_20220719_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='finishedHomework',
            field=models.ManyToManyField(blank=True, related_name='homework', to='home.Lessons', verbose_name='الواجبات التي تم ارسالها'),
        ),
        migrations.AlterField(
            model_name='student',
            name='watchedlecs',
            field=models.ManyToManyField(blank=True, related_name='wathedlecs', to='home.Lessons', verbose_name='المحاضرات المنتهيه'),
        ),
    ]
