# Generated by Django 3.2.9 on 2021-12-09 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20211129_0756'),
        ('reports', '0002_examreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreport',
            name='asknumber',
            field=models.IntegerField(verbose_name='عدد الاسئله'),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='correctAnswers',
            field=models.IntegerField(verbose_name='الاجابات الصحيحه'),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lessons', verbose_name='واجب درس'),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
    ]
