# Generated by Django 3.2.9 on 2021-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20211209_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreport',
            name='presentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='النسبه المئويه'),
        ),
    ]
