# Generated by Django 3.2.9 on 2021-12-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_examreport_presentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examreport',
            name='asknumber',
        ),
        migrations.RemoveField(
            model_name='examreport',
            name='correctAnswers',
        ),
        migrations.RemoveField(
            model_name='examreport',
            name='presentage',
        ),
    ]
