# Generated by Django 3.2.9 on 2021-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20211209_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreport',
            name='asknumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الاسئله'),
        ),
        migrations.AddField(
            model_name='examreport',
            name='correctAnswers',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الاجابات الصحيحه'),
        ),
        migrations.AddField(
            model_name='examreport',
            name='presentage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='النسبه المئويه'),
        ),
    ]
