# Generated by Django 3.2.9 on 2021-12-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20211209_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreport',
            name='asknumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الاسئله'),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='correctAnswers',
            field=models.IntegerField(blank=True, null=True, verbose_name='الاجابات الصحيحه'),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='presentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='النسبه المئويه'),
        ),
    ]
