# Generated by Django 3.2.9 on 2021-12-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211129_0756'),
        ('reports', '0009_rename_examreport_homeworkreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkreport',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lessons', unique=True, verbose_name='واجب درس'),
        ),
    ]
