# Generated by Django 3.2.9 on 2021-12-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211129_0756'),
        ('reports', '0010_alter_homeworkreport_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkreport',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lessons', verbose_name='واجب درس'),
        ),
    ]
