# Generated by Django 3.2.9 on 2021-12-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_homeworkreport_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkreport',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='homeworkreport',
            name='wrongAnswers',
            field=models.IntegerField(blank=True, null=True, verbose_name='الإجابات الخاطئه'),
        ),
    ]
