# Generated by Django 3.2.9 on 2021-12-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_report_homerport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='homerport',
        ),
        migrations.AddField(
            model_name='report',
            name='homerport',
            field=models.ManyToManyField(to='reports.homeworkReport', verbose_name='واجبات الطالب'),
        ),
    ]
