# Generated by Django 3.2.9 on 2021-12-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_exams_exam'),
        ('reports', '0016_auto_20211213_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreport',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.exam', verbose_name='امتحان'),
        ),
        migrations.AlterField(
            model_name='report',
            name='examReport',
            field=models.ManyToManyField(blank=True, to='reports.examReport', verbose_name='امتحانات الطالب'),
        ),
        migrations.AlterField(
            model_name='report',
            name='homerport',
            field=models.ManyToManyField(blank=True, to='reports.homeworkReport', verbose_name='واجبات الطالب'),
        ),
    ]
