# Generated by Django 3.2.9 on 2021-11-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211123_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='catgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم التصنيف')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='catname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.catgory', verbose_name='يتبع'),
        ),
    ]
