# Generated by Django 3.2.9 on 2021-12-15 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211129_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catgory',
            options={'verbose_name': 'الفرع', 'verbose_name_plural': 'الفروع'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'الدرس', 'verbose_name_plural': 'الدروس'},
        ),
    ]
