# Generated by Django 3.2.9 on 2021-12-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211215_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catgory',
            options={'managed': False, 'verbose_name': 'الفرع', 'verbose_name_plural': 'الفروع'},
        ),
    ]
