# Generated by Django 3.2.9 on 2021-12-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_exam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exams',
            new_name='exam',
        ),
    ]
