# Generated by Django 3.2.9 on 2021-12-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_exams_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'امتحان', 'verbose_name_plural': 'الإمتحانات'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'الأسئله', 'verbose_name_plural': 'الأسئله'},
        ),
        migrations.AlterField(
            model_name='task',
            name='quest',
            field=models.TextField(blank=True, null=True, verbose_name='السؤال'),
        ),
    ]
